insert into profiles (id, name, phone, location, preferred_language, is_verified, bio_th, bio_en) values
('neighbor-somchai', 'สมชาย ใจดี', '0812340101', 'krabi-town', 'th', true,
 'ช่างแอร์และซ่อมมอเตอร์ไซค์ในตัวเมืองกระบี่ ทำงานตรงเวลา',
 'AC tech and motorbike mechanic in Krabi Town. Shows up on time.'),
('neighbor-malee', 'มาลี ศรีสุข', '0812340102', 'ao-nang', 'th', true,
 'รักสวนและทะเล อ่าวนาง ยืมของกันได้เลย',
 'Garden and sea lover in Ao Nang. Happy to lend what I have.'),
('neighbor-niran', 'นิรันดร์ ทอง', '0812340103', 'klong-muang', 'th', false,
 'มีเครื่องมือก่อสร้าง แถวคลองม่วง',
 'Building tools around Klong Muang.'),
('neighbor-emma', 'Emma Walsh', '0812340104', 'ao-nang', 'en', true,
 'สอนภาษาอังกฤษ และมีบอร์ด SUP ให้ยืม',
 'English tutor with a SUP board to lend.'),
('neighbor-lukas', 'Lukas Weber', '0812340105', 'nong-thale', 'en', true,
 'มีกระบะและสกู๊ตเตอร์ ช่วยขนของได้',
 'Pickup truck and scooter. Happy to help with moves.'),
('neighbor-ploy', 'พลอย จันทร์', '0812340106', 'krabi-noi', 'th', true,
 'สอนภาษาไทย และมีของเด็กให้แบ่งปัน',
 'Thai teacher sharing baby gear from Krabi Noi.'),
('neighbor-james', 'James Park', '0812340107', 'ao-nang', 'en', false,
 'ตั้งแคมป์และตกปลาตามชายฝั่ง',
 'Camping and fishing along the coast.'),
('neighbor-kamon', 'กมล รัตนา', '0812340108', 'krabi-town', 'th', true,
 'ช่างไฟบ้าน งานเล็กงานใหญ่',
 'House electrician for small and larger jobs.')
on conflict (id) do nothing;

insert into items (id, user_id, title_th, title_en, description_th, description_en, category, type, price_per_day, deposit, status, images, district, lat, lng, condition, source_language) values
('item-kayak', 'neighbor-malee',
 'คายัคทะเล 2 ที่นั่ง', 'Two-person sea kayak',
 'คายัคคงทน พร้อมพาย 2 ชุด รับที่หาดอ่าวนาง ช่วงเช้าหรือเย็น',
 'Stable sea kayak with two paddles. Pickup on Ao Nang beach morning or evening.',
 'watersports', 'lend', 200, 1000, 'available', '["/listings/kayak.jpg"]',
 'ao-nang', 8.0381, 98.8195, 'good', 'th'),
('item-drill', 'neighbor-niran',
 'สว่านไร้สาย 18V', '18V cordless drill',
 'มีดอกสว่านชุดใหญ่ แบต 2 ก้อน เหมาะงานบ้าน',
 'Comes with a full bit set and two batteries. Fine for home jobs.',
 'tools', 'lend', 80, 500, 'available', '["/listings/drill.jpg"]',
 'klong-muang', 8.0912, 98.7488, 'like_new', 'th'),
('item-ladder', 'neighbor-niran',
 'บันไดอะลูมิเนียม 8 ขั้น', '8-step aluminium ladder',
 'เบา แข็งแรง ใช้ทาสีหรือเปลี่ยนหลอดไฟ',
 'Light and sturdy. Good for painting or changing bulbs.',
 'tools', 'lend', 50, 300, 'available', '["/listings/ladder.jpg"]',
 'klong-muang', 8.0864, 98.7512, 'good', 'th'),
('item-scooter', 'neighbor-lukas',
 'สกู๊ตเตอร์ออโต้ รายวัน', 'Automatic scooter, daily',
 'เติมน้ำมันคืนมาเท่าที่รับ หมวกกันน็อก 2 ใบ',
 'Return with the same fuel level. Two helmets included.',
 'vehicles', 'lend', 350, 3000, 'available', '["/listings/scooter.jpg"]',
 'nong-thale', 8.0655, 98.851, 'good', 'en'),
('item-garden', 'neighbor-malee',
 'ชุดเครื่องมือสวน', 'Garden tool set',
 'กรรไกร เสียม บัวรดน้ำ ให้ยืมฟรีถ้าดูแลคืนสภาพดี',
 'Shears, trowel, watering can. Free if returned clean.',
 'garden', 'lend', 0, 0, 'available', '["/listings/garden.jpg"]',
 'ao-nang', 8.0412, 98.8264, 'good', 'th'),
('item-sup', 'neighbor-emma',
 'บอร์ด SUP พร้อมพาย', 'Stand-up paddleboard and paddle',
 'บอร์ดพองลม เหมาะน้ำสงบแถวอ่าวนาง สอนขึ้นบอร์ดได้ถ้าต้องการ',
 'Inflatable SUP for calm Ao Nang water. I can show you the basics.',
 'watersports', 'lend', 250, 1500, 'available', '["/listings/paddleboard.jpg"]',
 'ao-nang', 8.0334, 98.8158, 'like_new', 'en'),
('item-stroller', 'neighbor-ploy',
 'รถเข็นเด็ก ใช้แล้วสภาพดี', 'Used baby stroller in good shape',
 'ลูกโตแล้ว ให้ฟรีกับครอบครัวที่ต้องการ รับที่กระบี่น้อย',
 'Our child outgrew it. Free for a family who needs it. Pickup in Krabi Noi.',
 'kids', 'gift', 0, 0, 'available', '["/listings/stroller.jpg"]',
 'krabi-noi', 8.1372, 98.9221, 'good', 'th'),
('item-tent', 'neighbor-james',
 'เต็นท์ 2 คน', 'Two-person tent',
 'กันน้ำ ใช้แคมป์ชายหาดได้ ส่งที่อ่าวนาง',
 'Waterproof, beach camping ready. Handover in Ao Nang.',
 'garden', 'lend', 150, 800, 'available', '["/listings/tent.jpg"]',
 'ao-nang', 8.0298, 98.8288, 'good', 'en'),
('item-fishing', 'neighbor-james',
 'ชุดเบ็ดตกปลา มือสอง', 'Used fishing rod set',
 'คันเบ็ด 2 อัน กล่องเหยื่อ ขายขาด ไม่ใช่ให้ยืม',
 'Two rods and a tackle box. For sale, not a loan.',
 'watersports', 'sell', 1200, null, 'available', '["/listings/fishing.jpg"]',
 'ao-nang', 8.044, 98.8302, 'fair', 'en'),
('item-wanted-saw', 'neighbor-emma',
 'ตามหาเลื่อยวงเดือน', 'Looking for a circular saw',
 'ต้องการยืม 1 วัน ตัดไม้ชั้นวางของ',
 'Need to borrow for one day to cut shelf boards.',
 'tools', 'wanted', null, null, 'available', '["/listings/drill.jpg"]',
 'ao-nang', 8.0363, 98.8222, null, 'en'),
('item-wanted-seat', 'neighbor-ploy',
 'ตามหาคาร์ซีทเด็ก', 'Looking for a baby car seat',
 'ใช้ชั่วคราว 2 สัปดาห์ มีญาติมาเยี่ยม',
 'Need for two weeks while family visits.',
 'kids', 'wanted', null, null, 'available', '["/listings/stroller.jpg"]',
 'krabi-noi', 8.1395, 98.9198, null, 'th')
on conflict (id) do nothing;

insert into services (id, user_id, title_th, title_en, description_th, description_en, category, offer_type, pricing_type, rate_thb, location_radius, status, images, district, lat, lng, available_times, source_language) values
('svc-ac', 'neighbor-somchai',
 'ล้างแอร์บ้าน', 'Home air-con cleaning',
 'ล้างคอยล์ ตรวจน้ำยา นัดล่วงหน้า 1 วัน ครอบคลุมตัวเมืองและหนองทะเล',
 'Coil clean and gas check. Book a day ahead. Covers town and Nong Thale.',
 'trades', 'offer', 'flat', 500, 12, 'active', '["/listings/ac.jpg"]',
 'krabi-town', 8.0863, 98.9063, 'Mon-Sat 08:00-17:00', 'th'),
('svc-moto', 'neighbor-somchai',
 'ซ่อมมอเตอร์ไซค์ถึงที่', 'Mobile motorbike repair',
 'เปลี่ยนยาง สตาร์ทไม่ติด ไฟไม่มา เรียกถึงที่ในรัศมี 10 กม.',
 'Tyres, no-start, electrics. I come to you within 10 km.',
 'trades', 'offer', 'hourly', 300, 10, 'active', '["/listings/scooter.jpg"]',
 'krabi-town', 8.0891, 98.9012, 'Everyday 09:00-19:00', 'th'),
('svc-garden', 'neighbor-malee',
 'ดูแลสวนและตัดหญ้า', 'Garden care and mowing',
 'ตัดหญ้า ตัดแต่งพุ่ม รดน้ำช่วงที่เจ้าของเดินทาง',
 'Mowing, hedge trim, watering while you travel.',
 'home', 'offer', 'hourly', 200, 8, 'active', '["/listings/garden.jpg"]',
 'ao-nang', 8.0363, 98.8222, 'Tue-Sun mornings', 'th'),
('svc-english', 'neighbor-emma',
 'สอนภาษาอังกฤษ สนทนา', 'Conversational English lessons',
 'เน้นพูดในชีวิตประจำวัน ร้านอาหาร งาน ราคาต่อชั่วโมง ที่อ่าวนางหรือออนไลน์',
 'Everyday speaking: cafes, work, errands. In Ao Nang or online.',
 'tutoring', 'offer', 'hourly', 400, 15, 'active', '["/listings/tent.jpg"]',
 'ao-nang', 8.0401, 98.821, 'Weekday evenings, weekend mornings', 'en'),
('svc-move', 'neighbor-lukas',
 'ขนของด้วยกระบะ', 'Pickup truck moving help',
 'กระบะพร้อมคนขับ ย้ายบ้าน ไปสนามบิน หรือตลาดวังใหญ่',
 'Truck plus driver. House moves, airport runs, or Wang Yai market.',
 'transport', 'offer', 'flat', 800, 25, 'active', '["/listings/pickup.jpg"]',
 'nong-thale', 8.0678, 98.8481, 'By appointment', 'en'),
('svc-thai', 'neighbor-ploy',
 'สอนภาษาไทย สำหรับชาวต่างชาติ', 'Thai lessons for newcomers',
 'อ่าน พูด คำกระบี่ในชีวิตประจำวัน สอนที่บ้านหรือคาเฟ่',
 'Reading, speaking, and Krabi daily phrases. At home or a cafe.',
 'tutoring', 'offer', 'hourly', 350, 12, 'active', '["/listings/stroller.jpg"]',
 'krabi-noi', 8.1395, 98.9198, 'Mon-Fri 10:00-16:00', 'th'),
('svc-electric', 'neighbor-kamon',
 'ช่างไฟบ้าน', 'Home electrician',
 'ปลั๊ก ไฟรั่ว ติดตั้งพัดลมและแอร์เล็ก ออกใบเสร็จได้',
 'Sockets, trips, fan and small AC installs. Receipts available.',
 'trades', 'offer', 'hourly', 400, 15, 'active', '["/listings/ladder.jpg"]',
 'krabi-town', 8.0922, 98.911, 'Mon-Sat', 'th'),
('svc-wanted-pool', 'neighbor-james',
 'ตามหาคนดูแลสระ', 'Looking for pool care',
 'วิลล่าเล็กที่อ่าวนาง ต้องการคนดูสารคลอรีนรายสัปดาห์',
 'Small Ao Nang villa. Need weekly chlorine and skimming.',
 'home', 'wanted', 'hourly', 250, 6, 'active', '["/listings/kayak.jpg"]',
 'ao-nang', 8.0363, 98.8222, 'Flexible', 'en')
on conflict (id) do nothing;

insert into reviews (id, reviewer_id, target_user_id, rating, comment_th, comment_en, source_language) values
('rev-1', 'neighbor-emma', 'neighbor-somchai', 5,
 'ล้างแอร์สะอาด ตรงเวลา แนะนำเลย',
 'AC came out spotless and he was on time. Highly recommend.',
 'en'),
('rev-2', 'neighbor-lukas', 'neighbor-somchai', 5,
 'ซ่อมสตาร์ทให้ถึงที่ ภายในชั่วโมง',
 'Came to the house and fixed a no-start within the hour.',
 'en'),
('rev-3', 'neighbor-james', 'neighbor-malee', 5,
 'คายัคสมบูรณ์ พายครบ ส่งง่าย',
 'Kayak was in great shape, paddles included, easy handover.',
 'en'),
('rev-4', 'neighbor-niran', 'neighbor-malee', 4,
 'เครื่องมือสวนครบ กลับมาสะอาด',
 'Garden set was complete. Returned it clean.',
 'th'),
('rev-5', 'neighbor-ploy', 'neighbor-emma', 5,
 'สอนอังกฤษเข้าใจง่าย ใจดี',
 'Patient English lessons. Clear and kind.',
 'th'),
('rev-6', 'neighbor-kamon', 'neighbor-lukas', 5,
 'กระบะสะอาด ช่วยยกของด้วย',
 'Clean truck and he helped lift the boxes.',
 'th'),
('rev-7', 'neighbor-malee', 'neighbor-ploy', 5,
 'สอนไทยสนุก ได้คำที่ใช้จริงในกระบี่',
 'Fun Thai lessons with phrases you actually use in Krabi.',
 'th'),
('rev-8', 'neighbor-emma', 'neighbor-kamon', 4,
 'แก้ไฟรั่วได้เร็ว ราคาแฟร์',
 'Fixed a tripping breaker quickly. Fair rate.',
 'en')
on conflict (id) do nothing;
