alter table services add column if not exists kind text not null default 'service';

delete from items;

update services set kind = 'service' where id in (
  'svc-ac', 'svc-moto', 'svc-garden', 'svc-english', 'svc-move', 'svc-thai', 'svc-electric'
);
update services set kind = 'service' where id = 'svc-wanted-pool';

insert into services (
  id, user_id, title_th, title_en, description_th, description_en,
  category, offer_type, pricing_type, rate_thb, location_radius, status,
  images, district, lat, lng, available_times, source_language, kind
) values
('help-paperwork', 'neighbor-ploy',
 'ช่วยเรื่องเอกสารภาษาไทย', 'Help with Thai paperwork',
 'ช่วยแปลและกรอกเอกสาร ธนาคาร โรงพยาบาล หรือ ตม. ไม่คิดเงินเพื่อนบ้าน',
 'Help filling and translating forms — bank, hospital or immigration. Free for neighbours.',
 'paperwork', 'offer', 'free', 0, 15, 'active', '["/listings/tent.jpg"]',
 'krabi-noi', 8.138, 98.918, 'Weekdays', 'th', 'help'),
('help-airport', 'neighbor-lukas',
 'รับส่งสนามบินให้เพื่อนบ้าน', 'Airport lift for neighbours',
 'มีกระบะ รับส่งกระบี่แอร์พอร์ต แลกกับค่าน้ำมันหรือช่วยงานอื่น',
 'Pickup truck to Krabi airport. Swap for fuel money or another favour.',
 'transport', 'offer', 'swap', 0, 30, 'active', '["/listings/pickup.jpg"]',
 'nong-thale', 8.066, 98.849, 'By arrangement', 'en', 'help'),
('help-pets', 'neighbor-malee',
 'ดูแลแมวตอนเจ้าของเดินทาง', 'Cat sitting while you travel',
 'แวะให้อาหารและเล่นด้วย แถวอ่าวนาง ฟรีถ้าอยู่ไม่เกิน 5 วัน',
 'Drop in to feed and play. Ao Nang. Free for trips under five days.',
 'pets', 'offer', 'free', 0, 6, 'active', '["/listings/garden.jpg"]',
 'ao-nang', 8.039, 98.824, 'Most mornings', 'th', 'help'),
('help-translate', 'neighbor-emma',
 'ช่วยแปลที่คลินิกหรือร้าน', 'Translate at clinics and shops',
 'ไปด้วยเป็นเพื่อนแปลไทย-อังกฤษ งานสั้น ๆ ไม่คิดเงิน',
 'Come along for Thai-English at clinics or shops. Short visits, no charge.',
 'paperwork', 'offer', 'free', 0, 10, 'active', '["/listings/tent.jpg"]',
 'ao-nang', 8.037, 98.821, 'Afternoons', 'en', 'help'),
('help-move', 'neighbor-james',
 'ตามหาคนช่วยยกโซฟา', 'Need two people to lift a sofa',
 'ย้ายโซฟาขึ้นชั้นสองที่อ่าวนาง ใช้เวลาประมาณหนึ่งชั่วโมง',
 'Move a sofa up one flight in Ao Nang. About an hour.',
 'daily', 'wanted', 'swap', 0, 5, 'active', '["/listings/pickup.jpg"]',
 'ao-nang', 8.034, 98.827, 'This weekend', 'en', 'help'),
('help-kids', 'neighbor-ploy',
 'ตามหาคนดูแลเด็ก 3 ชม.', 'Need childcare for 3 hours',
 'ลูก 4 ขวบ ที่กระบี่น้อย ต้องการคนอยู่บ้านช่วงบ่ายวันพุธ',
 'Four-year-old in Krabi Noi. Need someone at home Wednesday afternoon.',
 'childcare', 'wanted', 'hourly', 150, 8, 'active', '["/listings/stroller.jpg"]',
 'krabi-noi', 8.141, 98.921, 'Wed 13:00-16:00', 'th', 'help'),
('job-house', 'neighbor-james',
 'รับแม่บ้านวิลล่า อ่าวนาง', 'Villa housekeeper, Ao Nang',
 'วิลล่าเล็ก 3 ห้อง ทำความสะอาด 3 วัน/สัปดาห์ เริ่มเดือนหน้า',
 'Small 3-bed villa. Cleaning three days a week. Start next month.',
 'household', 'offer', 'monthly', 18000, 8, 'active', '["/listings/ac.jpg"]',
 'ao-nang', 8.032, 98.825, 'Mon Wed Fri mornings', 'en', 'job'),
('job-dive', 'neighbor-emma',
 'ร้านดำน้ำรับผู้ช่วยร้าน', 'Dive shop floor assistant',
 'ต้อนรับลูกค้า เช็คอุปกรณ์ ภาษาอังกฤษได้ รายวัน',
 'Greet guests and check kit. English useful. Paid by the day.',
 'tourism', 'offer', 'daily', 800, 12, 'active', '["/listings/kayak.jpg"]',
 'ao-nang', 8.041, 98.818, 'Tue-Sun', 'en', 'job'),
('job-shop', 'neighbor-somchai',
 'ร้านซ่อมมอไซค์รับผู้ช่วย', 'Motorbike shop helper wanted',
 'ล้างรถ จัดอะไหล่ เรียนรู้งานช่าง ตัวเมืองกระบี่',
 'Wash bikes, sort parts, learn the trade. Krabi Town workshop.',
 'trades', 'offer', 'daily', 700, 10, 'active', '["/listings/scooter.jpg"]',
 'krabi-town', 8.087, 98.904, 'Mon-Sat 09:00-17:00', 'th', 'job'),
('job-bar', 'neighbor-lukas',
 'หางานบาร์ ช่วงเย็น อ่าวนาง', 'Looking for evening bar work',
 'มีประสบการณ์บาร์ในเยอรมนี พร้อมทำงาน อ่าวนางหรือหนองทะเล',
 'Bar experience from Germany. Available evenings, Ao Nang or Nong Thale.',
 'hospitality', 'wanted', 'hourly', 150, 15, 'active', '["/listings/tent.jpg"]',
 'nong-thale', 8.069, 98.847, 'Evenings', 'en', 'job'),
('job-build', 'neighbor-niran',
 'รับงานก่อสร้าง รายวัน', 'Available for building work, daily',
 'ยกของ ฉาบ งานไซต์ คลองม่วงและตัวเมือง มีรถเอง',
 'Labour, plaster, site work. Klong Muang and town. Own transport.',
 'construction', 'wanted', 'daily', 600, 20, 'active', '["/listings/ladder.jpg"]',
 'klong-muang', 8.09, 98.75, 'Anytime', 'th', 'job'),
('job-wait', 'neighbor-kamon',
 'ร้านอาหารชายหาดรับพนักงานเสิร์ฟ', 'Beach restaurant hiring waitstaff',
 'ร้านอาหารอ่าวนาง กะเย็น ทิปหารแบ่ง เริ่มได้ทันที',
 'Ao Nang beach restaurant, evening shift. Tips shared. Can start now.',
 'hospitality', 'offer', 'daily', 650, 6, 'active', '["/listings/tent.jpg"]',
 'ao-nang', 8.036, 98.82, '17:00-23:00', 'th', 'job')
on conflict (id) do nothing;
