/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CreateRouteImport } from './routes/create'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as ServiceIdRouteImport } from './routes/service.$id'
import { Route as ApiAgentListingsRouteImport } from './routes/api/agent.listings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatsRoute,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIdRoute = ServiceIdRouteImport.update({
  id: '/service/$id',
  path: '/service/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentListingsRoute = ApiAgentListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/chats': typeof ChatsRouteWithChildren
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/chats/$id': typeof ChatsIdRoute
  '/item/$id': typeof ItemIdRoute
  '/service/$id': typeof ServiceIdRoute
  '/api/agent/listings': typeof ApiAgentListingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/chats': typeof ChatsRouteWithChildren
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/chats/$id': typeof ChatsIdRoute
  '/item/$id': typeof ItemIdRoute
  '/service/$id': typeof ServiceIdRoute
  '/api/agent/listings': typeof ApiAgentListingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/chats': typeof ChatsRouteWithChildren
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/chats/$id': typeof ChatsIdRoute
  '/item/$id': typeof ItemIdRoute
  '/service/$id': typeof ServiceIdRoute
  '/api/agent/listings': typeof ApiAgentListingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/chats'
    | '/create'
    | '/login'
    | '/search'
    | '/api/agent'
    | '/chats/$id'
    | '/item/$id'
    | '/service/$id'
    | '/api/agent/listings'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/chats'
    | '/create'
    | '/login'
    | '/search'
    | '/api/agent'
    | '/chats/$id'
    | '/item/$id'
    | '/service/$id'
    | '/api/agent/listings'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/chats'
    | '/create'
    | '/login'
    | '/search'
    | '/api/agent'
    | '/chats/$id'
    | '/item/$id'
    | '/service/$id'
    | '/api/agent/listings'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  ItemIdRoute: typeof ItemIdRoute
  ServiceIdRoute: typeof ServiceIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$id': {
      id: '/service/$id'
      path: '/service/$id'
      fullPath: '/service/$id'
      preLoaderRoute: typeof ServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/listings': {
      id: '/api/agent/listings'
      path: '/listings'
      fullPath: '/api/agent/listings'
      preLoaderRoute: typeof ApiAgentListingsRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatsRouteChildren {
  ChatsIdRoute: typeof ChatsIdRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsIdRoute: ChatsIdRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

interface ApiAgentRouteChildren {
  ApiAgentListingsRoute: typeof ApiAgentListingsRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentListingsRoute: ApiAgentListingsRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ChatsRoute: ChatsRouteWithChildren,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  ItemIdRoute: ItemIdRoute,
  ServiceIdRoute: ServiceIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
